package com.brzjomo.rebirthinmcihaveasystemforcultivatingimmortals.init;

import net.minecraft.loot.LootTables;
import net.minecraft.util.Identifier;

public class ModLootTables {
    public static final Identifier SIMPLE_DUNGEON_CHEST_ID = LootTables.SIMPLE_DUNGEON_CHEST;
    public static final Identifier BURIED_TREASURE_CHEST_ID = LootTables.BURIED_TREASURE_CHEST;
    public static final Identifier DESERT_PYRAMID_CHEST_ID = LootTables.DESERT_PYRAMID_CHEST;
    public static final Identifier JUNGLE_TEMPLE_CHEST_ID = LootTables.JUNGLE_TEMPLE_CHEST;
    public static final Identifier SHIPWRECK_TREASURE_CHEST_ID = LootTables.SHIPWRECK_TREASURE_CHEST;
    public static final Identifier UNDERWATER_RUIN_BIG_CHEST_ID = LootTables.UNDERWATER_RUIN_BIG_CHEST;
    public static final Identifier FISHING_TREASURE_GAMEPLAY_ID = LootTables.FISHING_TREASURE_GAMEPLAY;
    public static final Identifier OCEAN_RUIN_COLD_ARCHAEOLOGY_ID = LootTables.OCEAN_RUIN_COLD_ARCHAEOLOGY;
    public static final Identifier OCEAN_RUIN_WARM_ARCHAEOLOGY_ID = LootTables.OCEAN_RUIN_WARM_ARCHAEOLOGY;
    public static final Identifier TRAIL_RUINS_RARE_ARCHAEOLOGY_ID = LootTables.TRAIL_RUINS_RARE_ARCHAEOLOGY;
    public static final Identifier SNIFFER_DIGGING_GAMEPLAY_ID = LootTables.SNIFFER_DIGGING_GAMEPLAY;
    public static final Identifier VILLAGE_ARMORER_CHEST_ID = LootTables.VILLAGE_ARMORER_CHEST;
    public static final Identifier VILLAGE_BUTCHER_CHEST_ID = LootTables.VILLAGE_BUTCHER_CHEST;
    public static final Identifier VILLAGE_CARTOGRAPHER_CHEST_ID = LootTables.VILLAGE_CARTOGRAPHER_CHEST;
    public static final Identifier VILLAGE_FISHER_CHEST_ID = LootTables.VILLAGE_FISHER_CHEST;
    public static final Identifier VILLAGE_FLETCHER_CHEST_ID = LootTables.VILLAGE_FLETCHER_CHEST;
    public static final Identifier VILLAGE_DESERT_HOUSE_CHEST_ID = LootTables.VILLAGE_DESERT_HOUSE_CHEST;
    public static final Identifier VILLAGE_MASON_CHEST_ID = LootTables.VILLAGE_MASON_CHEST;
    public static final Identifier VILLAGE_PLAINS_CHEST_ID = LootTables.VILLAGE_PLAINS_CHEST;
    public static final Identifier VILLAGE_SAVANNA_HOUSE_CHEST_ID = LootTables.VILLAGE_SAVANNA_HOUSE_CHEST;
    public static final Identifier VILLAGE_SHEPARD_CHEST_ID = LootTables.VILLAGE_SHEPARD_CHEST;
    public static final Identifier VILLAGE_SNOWY_HOUSE_CHEST_ID = LootTables.VILLAGE_SNOWY_HOUSE_CHEST;
    public static final Identifier VILLAGE_TAIGA_HOUSE_CHEST_ID = LootTables.VILLAGE_TAIGA_HOUSE_CHEST;
    public static final Identifier VILLAGE_TANNERY_CHEST_ID = LootTables.VILLAGE_TANNERY_CHEST;
    public static final Identifier VILLAGE_TEMPLE_CHEST_ID = LootTables.VILLAGE_TEMPLE_CHEST;
    public static final Identifier VILLAGE_TOOLSMITH_CHEST_ID = LootTables.VILLAGE_TOOLSMITH_CHEST;
    public static final Identifier VILLAGE_WEAPONSMITH_CHEST_ID = LootTables.VILLAGE_WEAPONSMITH_CHEST;
    public static final Identifier ABANDONED_MINESHAFT_CHEST_ID = LootTables.ABANDONED_MINESHAFT_CHEST;
    public static final Identifier SHIPWRECK_MAP_CHEST_ID = LootTables.SHIPWRECK_MAP_CHEST;
    public static final Identifier RUINED_PORTAL_CHEST_ID = LootTables.RUINED_PORTAL_CHEST;
    public static final Identifier END_CITY_TREASURE_CHEST_ID = LootTables.END_CITY_TREASURE_CHEST;
    public static final Identifier NETHER_BRIDGE_CHEST_ID = LootTables.NETHER_BRIDGE_CHEST;
    public static final Identifier ANCIENT_CITY_CHEST_ID = LootTables.ANCIENT_CITY_CHEST;

    // ID list
    public static final Identifier[] LOOT_TABLE_INSERT_NIGHTFALL_TELEPORT_GEM_ID_LIST = {SIMPLE_DUNGEON_CHEST_ID, BURIED_TREASURE_CHEST_ID, DESERT_PYRAMID_CHEST_ID,
            JUNGLE_TEMPLE_CHEST_ID, SHIPWRECK_TREASURE_CHEST_ID, UNDERWATER_RUIN_BIG_CHEST_ID, FISHING_TREASURE_GAMEPLAY_ID, TRAIL_RUINS_RARE_ARCHAEOLOGY_ID,
            SNIFFER_DIGGING_GAMEPLAY_ID, VILLAGE_FISHER_CHEST_ID, VILLAGE_TEMPLE_CHEST_ID, VILLAGE_TOOLSMITH_CHEST_ID, ABANDONED_MINESHAFT_CHEST_ID,
            SHIPWRECK_MAP_CHEST_ID, RUINED_PORTAL_CHEST_ID, END_CITY_TREASURE_CHEST_ID, NETHER_BRIDGE_CHEST_ID, ANCIENT_CITY_CHEST_ID,
            OCEAN_RUIN_WARM_ARCHAEOLOGY_ID, VILLAGE_PLAINS_CHEST_ID, VILLAGE_TANNERY_CHEST_ID};

    public static final Identifier[] LOOT_TABLE_INSERT_BLESS_TELEPORT_GEM_ID_LIST = {SIMPLE_DUNGEON_CHEST_ID, BURIED_TREASURE_CHEST_ID, DESERT_PYRAMID_CHEST_ID,
            JUNGLE_TEMPLE_CHEST_ID, SHIPWRECK_TREASURE_CHEST_ID, UNDERWATER_RUIN_BIG_CHEST_ID, FISHING_TREASURE_GAMEPLAY_ID, TRAIL_RUINS_RARE_ARCHAEOLOGY_ID,
            SNIFFER_DIGGING_GAMEPLAY_ID, VILLAGE_FISHER_CHEST_ID, VILLAGE_TEMPLE_CHEST_ID, VILLAGE_TOOLSMITH_CHEST_ID, ABANDONED_MINESHAFT_CHEST_ID,
            SHIPWRECK_MAP_CHEST_ID, RUINED_PORTAL_CHEST_ID, END_CITY_TREASURE_CHEST_ID, NETHER_BRIDGE_CHEST_ID, ANCIENT_CITY_CHEST_ID,
            OCEAN_RUIN_COLD_ARCHAEOLOGY_ID, VILLAGE_SAVANNA_HOUSE_CHEST_ID, VILLAGE_WEAPONSMITH_CHEST_ID};
}
